name: Caller Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
      
run-name: ${{ github.actor }} is testing out GitHub Actions
env:
  GH_TOKEN: ${{ github.token }}

jobs:

  trigger:
    runs-on: ubuntu-latest

    steps:

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Workflow call
        shell: pwsh
        run: |
          gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/iss-milestone/TestRepoDispatch/actions/workflows/reusable_workflow.yaml/dispatches -f 'ref=main' -f 'inputs[test-input]=Input passed by gh'