name: Caller Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
      
run-name: ${{ github.actor }} is testing out GitHub Actions
env:
  GH_TOKEN: ${{ github.token }}

jobs:
    
  workflow-call:
    uses: iss-milestone/TestRepoDispatch/.github/workflows/reusable_workflow.yaml@main
    with:
      test-input: 'This is a test input'
    permissions: # Needed to be able to create tag (when publishing new package)
      contents: write
      actions: write
      checks: write
      pull-requests: write


  workflow-dispatch:
    runs-on: ubuntu-latest
    
    permissions: # Needed to be able to create tag (when publishing new package)
      contents: write
      actions: write
      checks: write
      pull-requests: write
    steps:

      - name: Check out repository code
        uses: actions/checkout@v4

      # - name: Workflow call
      #   uses: iss-milestone/TestRepoDispatch/.github/workflows/reusable_workflow.yaml@main
      #   with:
      #     test-input: 'This is a test input'

      - name: Workflow dispatch
        shell: bash
        run: |
          gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/iss-milestone/TestRepoDispatch/actions/workflows/reusable_workflow.yaml/dispatches -f 'ref=main'