name: Caller Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
      
run-name: ${{ github.actor }} is testing out GitHub Actions  🚀

jobs:

  trigger:
    runs-on: ubuntu-latest

    steps:

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: trigger the automated test in another repo
        uses: iss-milestone/reusable_workflow
        with:
          token: '${{ secrets.PAT_TOKEN }}'
          repository: iss-milestone/TestRepoDispatch 
          event-type: reusable-call

      - name: my-step
        shell: pwsh
        run: |
          gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/iss-milestone/TestRepoDispatch/actions/workflows/reusable_workflow.yaml/dispatches -f 'ref=main' -f 'inputs[test-input]=Input passed by gh'